config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'static_pages/home'

  resources :today_tasks, :only => [:index, :update]

  #get 'tasks/select', to: 'tasks#index'
  #post 'tasks/select', to: 'select_tasks#create'

  resources :tasks, :only => [:index, :create, :destroy]
  get 'select', to: 'tasks#select_index'
  patch 'tasks/select', to: 'tasks#select_update'

  resources :historys, :only => [:index]  

  root :to => 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  #validates :content, presence: true, length: { minimum: 1 }
  
  # ステータス（タスク状態）
  STATUS_INCOMPLETE = 0   # 未完
  STATUS_COMPLETE = 1     # 完了
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  
  has_many :tasks

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/historys_controller.rb
class HistorysController < ApplicationController
  def index
    @tasks = current_user.tasks.where(status: Task::STATUS_COMPLETE).order(:updated_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:destroy]
  
  def index
    @tasks = current_user.tasks.where(selected: false).where(status: Task::STATUS_INCOMPLETE)
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params)
    # ★あとでmigrateファイルにデフォルト値の設定を追加
    @task.user_id = current_user.id
    @task.selected = false
    @task.status = Task::STATUS_INCOMPLETE

    if @task.save
      redirect_back fallback_location: root_path, notice: 'Task was successfully created.'
    else
      render :index
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.' 
  end
  
  def select_index
    @tasks = current_user.tasks.where(selected: false).where(status: Task::STATUS_INCOMPLETE)
    @task = Task.new
  end
  
  def select_update
    order = 1
    params["checked"]["id"].each do |e|
      task = current_user.tasks.find(e)
      task.order = order
      order += 1
      task.selected = true
      task.save
    end
    
    redirect_to today_tasks_path
  end
  
  private
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:content)
    end
  
end

app/controllers/today_tasks_controller.rb
class TodayTasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:update, :unselect]

  def index
    @tasks = current_user.tasks.where(selected: true).order(:order)
    @task = Task.new

  end
  
  def update
    if params[:btn_id] == '0'
      @task.status = Task::STATUS_COMPLETE
    else
      @task.selected = false
    end

    if @task.save
    else
      render :index
    end
    
    tasks = current_user.tasks.where(selected: true).order(:order)
    tasks.each do |task|
      if task.status == Task::STATUS_INCOMPLETE
        # 未完了のタスクがあれば今からやるタスク画面にリダイレクト
        redirect_back fallback_location: root_path, notice: 'Task was successfully complete.'  and return
      end
    end
    
    # すべてのタスクが完了したら、すべて選択を外す
    tasks.each do |task|
      task.selected = false
      task.save
    end
    if params[:btn_id] == '0'
      message = 'Task was all complete.'
    end
    redirect_to select_url, notice: message and return
      
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "KyoYaru"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
  def bootstrap_class(flash_type)
    case flash_type
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/historys_helper.rb
module HistorysHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/today_todos_helper.rb
module TodayTodosHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/historys/index.html.erb
<% provide :title, "TaskHistory" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>過去のタスク</h1>
    
    <% @tasks.each do |task| %>
      <ul class="list-unstyled">
        <li><%= task.updated_at.strftime("%Y年%m月%d日 %H時%M分") %>
            <%= task.content %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- アプリロゴ -->
  <%= link_to "Kyo Yaru", '/', id: "logo", class: "navbar-brand" %>
  <!-- レスポンシブメニューボタン：lg -->
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- 右寄せメニュー -->
  <div class="collapse navbar-collapse d-lg-flex flex-row-reverse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% if current_user.tasks.where(selected: true).count >= 1 %>
          <li class="nav-item">
            <%= link_to "今やるタスク", today_tasks_url, method: :get, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "タスク選択", 'select', method: :get, class: "nav-link" %>
          </li
        <% end %>
        <li class="nav-item">
          <%= link_to "タスクリスト", tasks_url, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "過去のタスク", historys_url, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
    <%= render 'layouts/header' %>

    <!-- フラッシュメッセージ表示 -->
    <div class="container-fluid p-0">
      <% flash.each do |key, value| %>
        <div class="alert <%= bootstrap_class(key) %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    
    <%= yield :javascript %>
  </body>
</html>

app/views/select_tasks/index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<% provide :title, "task_select" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>タスク選択</h1>
    <h2>今からやるタスクを選択</h2>
    
    <div class="row">
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <ul class="list-group sortable" style="height: 200px">
              <% @tasks.each do |task| %>
              	<li class="list-group-item" value="<%= task.id %>"><%= task.content %> </li>
              <% end %>
    
            </ul>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <ul class="list-group sortable" style="height: 200px" id="selected_ul">
            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 新登録ボタン -->
    <div class="row mt-3">
      <div class="col-sm">
        <a href="javascript:void(0)" onclick="submit_form_select();" class="btn btn-success">選択完了</a>
      </div>
    </div>
    
    <form action="/tasks/select" method="post" id="form_select">
      <!--
      <p><% @tasks.each do |task| %>
      	<%= check_box_tag 'checked[id][]', task.id %>
      	<%= task.content %>
      	
      	<% end %>
      </p>
      
      <p>
      <input type="submit" value="登録する">
      </p>
      -->
      
      <input type="hidden" name="authenticity_token" value="r6fFH/olgV75lxN8y1k8OzmcbgIZ6yiJO2Hu/Wq9twKaiQE73m7nilqV6faTlC8KJMIyBN1HCFbKuptY+urnAA==" />
    
    </form>
    
    </br></br>
    <%= render './shared/form', task: @task %>
  </div>
</div>

<% content_for :javascript do %>
<script>
  $(function() {
    $(".sortable").sortable({
      connectWith: ".sortable"
    });
  });

  // 新登録ボタン
  function submit_form_select() {
    // 右の移動されたタスク ID を取ってくる
    $("#selected_ul li").each(function(index) {
      var task_id = $(this).prop("value");

      // そのタスク ID を無理やりフォームに hidden でぶっ込む
      $('<input>', { type:'hidden', name: "checked[id][]", value: task_id }).appendTo($("#form_select"));
    });

    // submit ボタンを押す
  　$("#form_select").submit();
  }
</script>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_field :content %>
  </div>
  
  <div class="actions">
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide :title, "home" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>Kyo Yaru</h1>
  
    <p>
      まずは3つのタスクに集中！他のことは考えない！
    </p>
  

    <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-primary badge-pill pr-4 pl-4" %>
    <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary badge-pill pr-4 pl-4" %>
        <%= link_to "ログイン", new_user_session_path,class: "btn btn-primary badge-pill pr-4 pl-4" %>
    <% end %>
  
  </div>

</div>
    

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<% provide :title, "task_list" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>タスクリスト</h1>
    
    <%= render './shared/form', task: @task %>

    <div class="task-list row">
      <% @tasks.each do |task| %>
        <div class="col-xs-12 col-lg-6 col-xl-3 fusen text-left" style="padding-left: 60px;">
          <ul class="list-unstyled">
            <li><%= task.content %></li>
            <span class="btn-task-del"><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/select_index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<% provide :title, "task_select" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>タスク選択</h1>
    <h2>今からやるタスクを選択</h2>
    
    <div class="row">
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <ul class="list-group sortable" style="height: 200px">
              <% @tasks.each do |task| %>
              	<li class="list-group-item" value="<%= task.id %>"><%= task.content %> </li>
              <% end %>
    
            </ul>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <ul class="list-group sortable" style="height: 200px" id="selected_ul">
            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 新登録ボタン -->
    <div class="row mt-3">
      <div class="col-sm">
        <a href="javascript:void(0)" onclick="submit_form_select();" class="btn btn-success">選択完了</a>
      </div>
    </div>
    
    <form action= <%= tasks_select_path %> method="post" id="form_select">
      <input type="hidden" name="_method" value="PATCH">
      <!--
      <p><% @tasks.each do |task| %>
      	<%= check_box_tag 'checked[id][]', task.id %>
      	<%= task.content %>
      	
      	<% end %>
      </p>
      
      <p>
      <input type="submit" value="登録する">
      </p>
      -->
      
      <input type="hidden" name="authenticity_token" value="r6fFH/olgV75lxN8y1k8OzmcbgIZ6yiJO2Hu/Wq9twKaiQE73m7nilqV6faTlC8KJMIyBN1HCFbKuptY+urnAA==" />
    
    </form>
    
    </br></br>
    <%= render './shared/form', task: @task %>
  </div>
</div>

<% content_for :javascript do %>
<script>
  $(function() {
    $(".sortable").sortable({
      connectWith: ".sortable"
    });
  });

  // 新登録ボタン
  function submit_form_select() {
    // 右の移動されたタスク ID を取ってくる
    $("#selected_ul li").each(function(index) {
      var task_id = $(this).prop("value");

      // そのタスク ID を無理やりフォームに hidden でぶっ込む
      $('<input>', { type:'hidden', name: "checked[id][]", value: task_id }).appendTo($("#form_select"));
    });

    // submit ボタンを押す
  　$("#form_select").submit();
  }
</script>
<% end %>

app/views/today_tasks/index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<% provide :title, "TodayTask" %>

<div class="container-fluid">
  <div class="p-5 text-center">
    <h1>今やるタスク</h1>
      <% @tasks.each do |task| %>
        <% if task.status == Task::STATUS_INCOMPLETE %>
          <div class="fusen text-left" style="padding-left: 60px; font-size: 64px">
            <ul class="list-unstyled">
              <li><%= task.content %></li>
            </ul>
          </div>
          
          <div class="center-block">
            <%= link_to '完了', today_task_path(task, btn_id: 0), method: :patch, class: "btn btn-primary btn-lg badge-pill pr-4 pl-4" %>
            <%= link_to 'あとでやる', today_task_path(task, btn_id: 1), method: :patch, class: "btn btn-primary btn-sm badge-pill pr-4 pl-4" %>
          </div>
          <% break %>
        <% end %>
      <% end %>
    
      </br></br>
      <p>こんどやる（思いついたタスクを登録）</p>
      <%= render './shared/form', task: @task %>
  </div>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_field :content %>
  </div>
  
  <div class="actions">
    <%= form.submit "登録" %>
  </div>
<% end %>